services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=news_user;Password=news_password;Database=news_db
    depends_on:
      - db
    networks:
      - app_network
        
  db:
    image: postgres:17
    container_name: news_feed_postgres
    restart: always
    networks:
      - app_network
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
networks:
  app_network:
    driver: bridge
        
volumes:
  db_data:
    
    